version: '3.8'
services:
  # 1. Database
  postgres:
    image: postgres:15-alpine
    container_name: ticket-booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8226
      POSTGRES_DB: ticket_booking_db
    ports:
      - "5432:5432"
    restart: always

  # 2. Redis Cache
  redis:
    image: redis:alpine
    container_name: ticket-booking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  # 3. Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ticket-booking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 4. Kafka 
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ticket-booking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 5. BACKEND APPLICATION
  backend:
    build: .
    container_name: ticket-booking-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticket_booking_db
      
      
      # Connect to Redis & Kafka Containers
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  redis-data: